// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesLibraryNew.Data;

namespace MoviesLibraryNew.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesLibraryNew.Models.FavoriteMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteMovies");
                });

            modelBuilder.Entity("MoviesLibraryNew.Models.FavoriteTvShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteTvShows");
                });

            modelBuilder.Entity("MoviesLibraryNew.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2021-05-26",
                            Poster = "https://image.tmdb.org/t/p/w300/rTh4K5uw9HypmpGslcKd4QfHl93.jpg",
                            Rating = 9,
                            Summary = "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
                            Title = "Cruella"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2021-05-25",
                            Poster = "https://image.tmdb.org/t/p/w300/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg",
                            Rating = 8,
                            Summary = "Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
                            Title = "The Conjuring: The Devil Made Me Do It"
                        },
                        new
                        {
                            Id = 3,
                            Date = "2021-04-22",
                            Poster = "https://image.tmdb.org/t/p/w300/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
                            Rating = 8,
                            Summary = "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
                            Title = "Wrath of Man"
                        },
                        new
                        {
                            Id = 4,
                            Date = "2021-03-31",
                            Poster = "https://image.tmdb.org/t/p/w300/bShgiEQoPnWdw4LBrYT5u18JF34.jpg",
                            Rating = 7,
                            Summary = "Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.",
                            Title = "The Unholy"
                        },
                        new
                        {
                            Id = 5,
                            Date = "2021-05-12",
                            Poster = "https://image.tmdb.org/t/p/w300/lcyKve7nXRFgRyms9M1bndNkKOx.jpg",
                            Rating = 6,
                            Summary = "Working in the shadow of an esteemed police veteran, brash Detective Ezekiel “Zeke” Banks and his rookie partner take charge of a grisly investigation into murders that are eerily reminiscent of the city’s gruesome past.  Unwittingly entrapped in a deepening mystery, Zeke finds himself at the center of the killer’s morbid game.",
                            Title = "Spiral: From the Book of Saw"
                        },
                        new
                        {
                            Id = 6,
                            Date = "2021-05-21",
                            Poster = "https://image.tmdb.org/t/p/w300/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg",
                            Rating = 7,
                            Summary = "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.",
                            Title = "A Quiet Place Part II"
                        },
                        new
                        {
                            Id = 7,
                            Date = "2021-05-14",
                            Poster = "https://image.tmdb.org/t/p/w300/z8CExJekGrEThbpMXAmCFvvgoJR.jpg",
                            Rating = 7,
                            Summary = "Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble: venturing into the quarantine zone to pull off the greatest heist ever attempted.",
                            Title = "Army of the Dead"
                        },
                        new
                        {
                            Id = 8,
                            Date = "2021-04-07",
                            Poster = "https://image.tmdb.org/t/p/w300/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg",
                            Rating = 8,
                            Summary = "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
                            Title = "Mortal Kombat"
                        },
                        new
                        {
                            Id = 9,
                            Date = "2021-03-24",
                            Poster = "https://image.tmdb.org/t/p/w300/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
                            Rating = 8,
                            Summary = "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
                            Title = "Godzilla vs. Kong"
                        },
                        new
                        {
                            Id = 10,
                            Date = "2021-05-27",
                            Poster = "https://image.tmdb.org/t/p/w300/ccsSqbpEqr2KK9eMvoeF8ERFCd5.jpg",
                            Rating = 7,
                            Summary = "Jack Halsey takes his wife, their adult kids, and a friend for a dream vacation in Kenya. But as they venture off alone into a wilderness park, their safari van is flipped over by an angry rhino, leaving them injured and desperate. Then, as two of them go in search of rescue, a bloody, vicious encounter with a leopard and a clan of hyenas incites a desperate fight for survival.",
                            Title = "Endangered Species"
                        },
                        new
                        {
                            Id = 11,
                            Date = "2021-04-29",
                            Poster = "https://image.tmdb.org/t/p/w300/rEm96ib0sPiZBADNKBHKBv5bve9.jpg",
                            Rating = 7,
                            Summary = "An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.",
                            Title = "Tom Clancy's Without Remorse"
                        },
                        new
                        {
                            Id = 12,
                            Date = "2021-03-03",
                            Poster = "https://image.tmdb.org/t/p/w300/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
                            Rating = 8,
                            Summary = "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
                            Title = "Raya and the Last Dragon"
                        },
                        new
                        {
                            Id = 13,
                            Date = "2021-05-05",
                            Poster = "https://image.tmdb.org/t/p/w300/xCEg6KowNISWvMh8GvPSxtdf9TO.jpg",
                            Rating = 7,
                            Summary = "A young boy finds himself pursued by two assassins in the Montana wilderness with a survival expert determined to protecting him - and a forest fire threatening to consume them all.",
                            Title = "Those Who Wish Me Dead"
                        },
                        new
                        {
                            Id = 14,
                            Date = "2020-10-16",
                            Poster = "https://image.tmdb.org/t/p/w300/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
                            Rating = 8,
                            Summary = "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
                            Title = "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train"
                        },
                        new
                        {
                            Id = 15,
                            Date = "2021-03-18",
                            Poster = "https://image.tmdb.org/t/p/w300/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
                            Rating = 8,
                            Summary = "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
                            Title = "Zack Snyder's Justice League"
                        },
                        new
                        {
                            Id = 16,
                            Date = "2021-04-30",
                            Poster = "https://image.tmdb.org/t/p/w300/vXHzO26mJaOt4VO7ZFiM6No5ScT.jpg",
                            Rating = 6,
                            Summary = "A lonesome stranger with nerves of steel must track down and kill a rogue hitman to satisfy an outstanding debt. But the only information he's been given is a time and location where to find his quarry. No name. No description. Nothing.",
                            Title = "The Virtuoso"
                        },
                        new
                        {
                            Id = 17,
                            Date = "2021-03-26",
                            Poster = "https://image.tmdb.org/t/p/w300/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
                            Rating = 8,
                            Summary = "Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a \"nobody.\" When two thieves break into his home one night, Hutch's unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.",
                            Title = "Nobody"
                        },
                        new
                        {
                            Id = 18,
                            Date = "2021-04-04",
                            Poster = "https://image.tmdb.org/t/p/w300/msI5a9TPnepx47JUb2vl88hb80R.jpg",
                            Rating = 8,
                            Summary = "On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!",
                            Title = "Miraculous World: Shanghai – The Legend of Ladydragon"
                        },
                        new
                        {
                            Id = 19,
                            Date = "2021-05-14",
                            Poster = "https://image.tmdb.org/t/p/w300/m6bUeV4mczG3z2YXXr5XDKPsQzv.jpg",
                            Rating = 7,
                            Summary = "A special crimes investigator forms an unlikely bond with a serial killer to bring down a global child sex trafficking syndicate.",
                            Title = "I Am All Girls"
                        },
                        new
                        {
                            Id = 20,
                            Date = "2021-04-02",
                            Poster = "https://image.tmdb.org/t/p/w300/dkokENeY5Ka30BFgWAqk14mbnGs.jpg",
                            Rating = 8,
                            Summary = "Drac tries out some new monster pets to help occupy Tinkles for playtime.",
                            Title = "Monster Pets: A Hotel Transylvania Short"
                        });
                });

            modelBuilder.Entity("MoviesLibraryNew.Models.TvShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TvShows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2021-06-09",
                            Poster = "https://image.tmdb.org/t/p/w300/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
                            Rating = 8,
                            Summary = "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat.",
                            Title = "Loki"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2016-01-25",
                            Poster = "https://image.tmdb.org/t/p/w300/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg",
                            Rating = 8,
                            Summary = "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
                            Title = "Lucifer"
                        },
                        new
                        {
                            Id = 3,
                            Date = "2014-10-07",
                            Poster = "https://image.tmdb.org/t/p/w300/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg",
                            Rating = 8,
                            Summary = "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.",
                            Title = "The Flash"
                        },
                        new
                        {
                            Id = 4,
                            Date = "2020-01-31",
                            Poster = "https://image.tmdb.org/t/p/w300/xUtOM1QO4r8w8yeE00QvBdq58N5.jpg",
                            Rating = 8,
                            Summary = "A small Norwegian town experiencing warm winters and violent downpours seems to be headed for another Ragnarök -- unless someone intervenes in time.",
                            Title = "Ragnarok"
                        },
                        new
                        {
                            Id = 5,
                            Date = "2021-03-19",
                            Poster = "https://image.tmdb.org/t/p/w300/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
                            Rating = 8,
                            Summary = "Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.",
                            Title = "The Falcon and the Winter Soldier"
                        },
                        new
                        {
                            Id = 6,
                            Date = "2017-09-25",
                            Poster = "https://image.tmdb.org/t/p/w300/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg",
                            Rating = 9,
                            Summary = "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives",
                            Title = "The Good Doctor"
                        },
                        new
                        {
                            Id = 7,
                            Date = "2005-03-27",
                            Poster = "https://image.tmdb.org/t/p/w300/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg",
                            Rating = 8,
                            Summary = "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
                            Title = "Grey's Anatomy"
                        },
                        new
                        {
                            Id = 8,
                            Date = "2021-02-23",
                            Poster = "https://image.tmdb.org/t/p/w300/vlv1gn98GqMnKHLSh0dNciqGfBl.jpg",
                            Rating = 8,
                            Summary = "After years of facing megalomaniacal supervillains, monsters wreaking havoc on Metropolis, and alien invaders intent on wiping out the human race, The Man of Steel aka Clark Kent and Lois Lane come face to face with one of their greatest challenges ever: dealing with all the stress, pressures and complexities that come with being working parents in today's society.",
                            Title = "Superman & Lois"
                        },
                        new
                        {
                            Id = 9,
                            Date = "2021-06-04",
                            Poster = "https://image.tmdb.org/t/p/w300/rgMfhcrVZjuy5b7Pn0KzCRCEnMX.jpg",
                            Rating = 8,
                            Summary = "On a perilous adventure across a post-apocalyptic world, a lovable boy who's half-human and half-deer searches for a new beginning with a gruff protector.",
                            Title = "Sweet Tooth"
                        },
                        new
                        {
                            Id = 10,
                            Date = "2017-01-26",
                            Poster = "https://image.tmdb.org/t/p/w300/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg",
                            Rating = 9,
                            Summary = "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.",
                            Title = "Riverdale"
                        },
                        new
                        {
                            Id = 11,
                            Date = "2018-06-12",
                            Poster = "https://image.tmdb.org/t/p/w300/fuVuDYrs8sxvEolnYr0wCSvtyTi.jpg",
                            Rating = 8,
                            Summary = "After spending seventeen years in prison unfairly, a talented songwriter seeks revenge on the men who sank her and killed her family.",
                            Title = "The Queen of Flow"
                        },
                        new
                        {
                            Id = 12,
                            Date = "2021-03-24",
                            Poster = "https://image.tmdb.org/t/p/w300/o7uk5ChRt3quPIv8PcvPfzyXdMw.jpg",
                            Rating = 8,
                            Summary = "Hell-bent on exacting revenge and proving he was framed for his sister's murder, Álex sets out to unearth much more than the crime's real culprit.",
                            Title = "Who Killed Sara?"
                        },
                        new
                        {
                            Id = 13,
                            Date = "2021-04-18",
                            Poster = "https://image.tmdb.org/t/p/w300/78aK4Msbr22A5PGa6PZV0pAvdwf.jpg",
                            Rating = 8,
                            Summary = "A detective in a small Pennsylvania town investigates a local murder while trying to keep her life from falling apart.",
                            Title = "Mare of Easttown"
                        },
                        new
                        {
                            Id = 14,
                            Date = "2021-05-04",
                            Poster = "https://image.tmdb.org/t/p/w300/WjQmEWFrOf98nT5aEfUfVYz9N2.jpg",
                            Rating = 9,
                            Summary = "The 'Bad Batch' of elite and experimental clones make their way through an ever-changing galaxy in the immediate aftermath of the Clone Wars.",
                            Title = "The Bad Batch"
                        },
                        new
                        {
                            Id = 15,
                            Date = "2021-03-26",
                            Poster = "https://image.tmdb.org/t/p/w300/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg",
                            Rating = 9,
                            Summary = "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.",
                            Title = "Invincible"
                        },
                        new
                        {
                            Id = 16,
                            Date = "2021-01-15",
                            Poster = "https://image.tmdb.org/t/p/w300/glKDfE6btIRcVB5zrjspRIs4r52.jpg",
                            Rating = 8,
                            Summary = "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.",
                            Title = "WandaVision"
                        },
                        new
                        {
                            Id = 17,
                            Date = "2011-04-17",
                            Poster = "https://image.tmdb.org/t/p/w300/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
                            Rating = 8,
                            Summary = "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            Id = 18,
                            Date = "2015-08-23",
                            Poster = "https://image.tmdb.org/t/p/w300/4UjiPdFKJGJYdxwRs2Rzg7EmWqr.jpg",
                            Rating = 8,
                            Summary = "What did the world look like as it was transforming into the horrifying apocalypse depicted in \"The Walking Dead\"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.",
                            Title = "Fear the Walking Dead"
                        },
                        new
                        {
                            Id = 19,
                            Date = "2018-10-25",
                            Poster = "https://image.tmdb.org/t/p/w300/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg",
                            Rating = 9,
                            Summary = "In a place where young witches, vampires, and werewolves are nurtured to be their best selves in spite of their worst impulses, Klaus Mikaelson’s daughter, 17-year-old Hope Mikaelson, Alaric Saltzman’s twins, Lizzie and Josie Saltzman, among others, come of age into heroes and villains at The Salvatore School for the Young and Gifted.",
                            Title = "Legacies"
                        },
                        new
                        {
                            Id = 20,
                            Date = "2021-05-07",
                            Poster = "https://image.tmdb.org/t/p/w300/9yxep7oJdkj3Pla9TD9gKflRApY.jpg",
                            Rating = 7,
                            Summary = "As the world's first generation of superheroes (who received their powers in the 1930s) become the revered elder guard in the present, their superpowered children struggle to live up to the legendary feats of their parents.",
                            Title = "Jupiter's Legacy"
                        });
                });

            modelBuilder.Entity("MoviesLibraryNew.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoviesLibraryNew.Models.FavoriteMovie", b =>
                {
                    b.HasOne("MoviesLibraryNew.Models.Movie", "Movie")
                        .WithMany("FavoriteMovie")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesLibraryNew.Models.User", "User")
                        .WithMany("FavoriteMovie")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoviesLibraryNew.Models.FavoriteTvShow", b =>
                {
                    b.HasOne("MoviesLibraryNew.Models.TvShow", "TvShow")
                        .WithMany("FavoriteTvShow")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesLibraryNew.Models.User", "User")
                        .WithMany("FavoriteTvShow")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
