// <auto-generated />
using ASP.NETCoreWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NETCoreWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.AnimeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(255);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Type")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.AnimeQuotesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CharDescreption")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Character")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Quote")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("AnimeQuotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharDescreption = "Roy Mustang is a character from Full Metal Alchemist who isn't afraid to speak his mind. In this quote, he talks about how imperfect the world can be. Ironically, alchemy can make it perfect via equivalent exchange.  But in the end, Roy says that the world being imperfect is 'perfect.' There is no such thing as perfection. Because once there is perfection, where do you go",
                            Character = "Roy Mustang (Full Metal Alchemist)",
                            Quote = "The world isn't perfect. But it's there for us, doing the best it can....that's what makes it so damn beautiful."
                        },
                        new
                        {
                            Id = 2,
                            CharDescreption = "Hitsugaya is the captain of Rangiku and one of the captains in Bleach. Known as one of the youngest captains ever, he is known for his strategies, brain and being as cold as ice. Speaking, Hitsugaya reiterates that even though they may grow and travel further apart, they should not disappear like fireworks",
                            Character = "Hitsugaya Toshiro (Bleach)",
                            Quote = "We are all like fireworks: we climb, we shine and always go our separate ways and become further apart. But even when that time comes, let's not disappear like a firework and continue to shine.. forever"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.UserInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.UsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sultan",
                            UserInfoId = 0
                        });
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.AnimeModel", b =>
                {
                    b.HasOne("ASP.NETCoreWebApplication.Models.UsersModel", "User")
                        .WithMany("Anime")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP.NETCoreWebApplication.Models.UsersModel", b =>
                {
                    b.HasOne("ASP.NETCoreWebApplication.Models.UserInfoModel", "UserInfo")
                        .WithOne("Users")
                        .HasForeignKey("ASP.NETCoreWebApplication.Models.UsersModel", "UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
